#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2016 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

echo "getting sources..."
  if [ ! -d mt7601u.git ]; then
    git clone https://github.com/kuba-moo/mt7601u.git mt7601u.git
  fi

  cd mt7601u.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf mt7601u-$GIT_REV
  cp -R mt7601u.git mt7601u-$GIT_REV

echo "cleaning sources..."
  rm -rf mt7601u-$GIT_REV/.git

echo "packing sources..."
  tar cvJf mt7601u-$GIT_REV.tar.xz mt7601u-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf mt7601u-$GIT_REV
  rm -rf mt7601u.git
