#!/bin/sh

################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2015 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################


PKG_NAME="oscam"
PKG_REPO="http://www.streamboard.tv/svn/oscam/trunk"

echo "getting sources..."
  svn checkout $PKG_REPO $PKG_NAME.svn

echo "getting version..."
  cd $PKG_NAME.svn
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$SVN_REV
  cp -R $PKG_NAME.svn $PKG_NAME-$SVN_REV

echo "packing sources..."
  tar cvJf $PKG_NAME-$SVN_REV.tar.xz $PKG_NAME-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME.svn
