#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2015 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

echo "getting sources..."
  if [ ! -d retroarch-joypad-autoconfig.git ]; then
    git clone https://github.com/libretro/retroarch-joypad-autoconfig.git retroarch-joypad-autoconfig.git
  fi

  cd retroarch-joypad-autoconfig.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf retroarch-joypad-autoconfig-$GIT_REV
  cp -R retroarch-joypad-autoconfig.git retroarch-joypad-autoconfig-$GIT_REV

echo "cleaning sources..."
  rm -rf retroarch-joypad-autoconfig-$GIT_REV/.git
  rm retroarch-joypad-autoconfig-$GIT_REV/.gitignore

echo "packing sources..."
  tar cvJf retroarch-joypad-autoconfig-$GIT_REV.tar.xz retroarch-joypad-autoconfig-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf retroarch-joypad-autoconfig-$GIT_REV
  rm -rf retroarch-joypad-autoconfig.git
