#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2015 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

echo "getting sources..."
  if [ ! -d core-info.git ]; then
    git clone https://github.com/libretro/libretro-super.git -b master core-info.git
  fi

  cd core-info.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf core-info-$GIT_REV
  cp -R core-info.git core-info-$GIT_REV

echo "cleaning sources..."
  rm -rf core-info-$GIT_REV/.git
  rm core-info-$GIT_REV/.gitignore

echo "packing sources..."
  tar cvJf core-info-$GIT_REV.tar.xz core-info-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf core-info-$GIT_REV
  rm -rf core-info.git
