#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2016 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

PKG_NAME="vdr-plugin-dvbapi"
PKG_REPO="git://github.com/manio/vdr-plugin-dvbapi.git"

echo "getting sources..."
  if [ ! -d $PKG_NAME.git ]; then
    git clone $PKG_REPO $PKG_NAME.git
  fi

  cd $PKG_NAME.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$GIT_REV
  cp -R $PKG_NAME.git $PKG_NAME-$GIT_REV

echo "cleaning sources..."
  rm -rf $PKG_NAME-$GIT_REV/.git

echo "packing sources..."
  tar cvJf $PKG_NAME-$GIT_REV.tar.xz $PKG_NAME-$GIT_REV

echo "remove temporary sourcedir..."
#  rm -rf $PKG_NAME-$GIT_REV
  rm -rf $PKG_NAME.git