#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2016 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

echo "getting sources..."
  if [ ! -d vdr-plugin-weatherforecast.git ]; then
    git clone git://projects.vdr-developer.org/vdr-plugin-weatherforecast.git vdr-plugin-weatherforecast.git
  fi

  cd vdr-plugin-weatherforecast.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf vdr-plugin-weatherforecast-$GIT_REV
  cp -R vdr-plugin-weatherforecast.git vdr-plugin-weatherforecast-$GIT_REV

echo "packing sources..."
  tar cvJf vdr-plugin-weatherforecast-$GIT_REV.tar.xz vdr-plugin-weatherforecast-$GIT_REV

echo "remove temporary sourcedir..."
#  rm -rf vdr-skin-weatherforecast-$GIT_REV
  rm -rf vdr-plugin-weatherforecast.git
