#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2015 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

echo "getting sources..."
  if [ ! -d vdr-plugin-zaphistory.git ]; then
    git clone git://projects.vdr-developer.org/vdr-plugin-zaphistory.git vdr-plugin-zaphistory.git
  fi

  cd vdr-plugin-zaphistory.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf vdr-plugin-zaphistory-$GIT_REV
  cp -R vdr-plugin-zaphistory.git vdr-plugin-zaphistory-$GIT_REV

echo "cleaning sources..."
  rm -rf vdr-plugin-zaphistory-$GIT_REV/.git

echo "packing sources..."
  tar cvJf vdr-plugin-zaphistory-$GIT_REV.tar.xz vdr-plugin-zaphistory-$GIT_REV

echo "remove temporary sourcedir..."
  rm -rf vdr-plugin-zaphistory-$GIT_REV
  rm -rf vdr-plugin-zaphistory.git
