#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2016 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

PKG_NAME="kodi"
PKG_VERSION=""
BRANCH="Jarvis"
GIT_REPO="git://github.com/xbmc/xbmc.git"
DEST_DIR="$PKG_NAME-$BRANCH"

echo "getting sources..."
  if [ ! -d $DEST_DIR.git ]; then
    git clone --depth 1 $GIT_REPO -b $BRANCH $DEST_DIR.git
  fi

  cd $DEST_DIR.git
  git pull

echo "getting version..."
  GIT_HASH=`git log -n1 --format=%h`
  VERSION_MAJOR=$(grep ^VERSION_MAJOR version.txt | cut -d" " -f2)
  VERSION_MINOR=$(grep ^VERSION_MINOR version.txt | cut -d" " -f2)
  VERSION_TAG=$(grep ^VERSION_TAG version.txt | cut -d" " -f2 | tr A-Z a-z)
  PKG_VERSION="$VERSION_MAJOR.$VERSION_MINOR-$VERSION_TAG-$GIT_HASH"
  # hack: empty version tag on release builds:
  if [ "$VERSION_TAG" = "version_tag" ] ; then
    PKG_VERSION="$VERSION_MAJOR.$VERSION_MINOR-$GIT_HASH"
  fi
  echo $PKG_VERSION
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$PKG_VERSION
  cp -R $DEST_DIR.git $PKG_NAME-$PKG_VERSION
  echo "$GIT_HASH" > $PKG_NAME-$PKG_VERSION/VERSION

echo "cleaning sources..."
  rm -rf $PKG_NAME-$PKG_VERSION/.git

echo "seperating theme..."
  rm -rf $PKG_NAME-theme-Confluence-$PKG_VERSION
  mv $PKG_NAME-$PKG_VERSION/addons/skin.confluence $PKG_NAME-theme-Confluence-$PKG_VERSION

echo "packing sources..."
  tar cvJf $PKG_NAME-$PKG_VERSION.tar.xz $PKG_NAME-$PKG_VERSION
  tar cvJf $PKG_NAME-theme-Confluence-$PKG_VERSION.tar.xz $PKG_NAME-theme-Confluence-$PKG_VERSION

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$PKG_VERSION
  rm -rf $PKG_NAME-theme-Confluence-$PKG_VERSION
