#!/bin/sh
################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.in.ua
#      Copyright (C) 2011-2015 Alexandr Zuyev (alex@alexelec.in.ua)
################################################################################

echo "getting sources..."
  if [ ! -d retroarch.git ]; then
    git clone https://github.com/libretro/retroarch.git -b master retroarch.git
  fi

  cd retroarch.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf retroarch-$GIT_REV
  cp -R retroarch.git retroarch-$GIT_REV

echo "cleaning sources..."
  rm -rf retroarch-$GIT_REV/.git
  rm retroarch-$GIT_REV/.gitignore

echo "packing sources..."
  tar cvJf retroarch-$GIT_REV.tar.xz retroarch-$GIT_REV

echo "remove temporary sourcedir..."
  #rm -rf retroarch-$GIT_REV
  rm -rf retroarch.git
