#!/bin/bash

################################################################################
#      This file is part of Alex@ELEC - http://www.alexelec.ru
#      Copyright (C) 2011-2015 Alexandr Zuyev (alex@alexelec.ru)
################################################################################

. config/options $1

if [ ! -z "$1" ]; then
  printf "%${BUILD_INDENT}c ${boldred}CLEAN${endcolor}    $1\n" ' '>&$SILENT_OUT
  export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))

  if [ "$CLEAN_SOURCES" = true ]; then
    rm -rf $SOURCES/$1
    return
  fi

  for i in $BUILD/$1-*; do
    if [ -d $i -a -f "$i/.openelec-unpack" ] ; then
      . "$i/.openelec-unpack"
      if [ "$STAMP_PKG_NAME" = "$1" ]; then
        printf "%${BUILD_INDENT}c ${boldred}*${endcolor} ${red}Removing $i ...${endcolor}\n" ' '>&$SILENT_OUT
        rm -rf $i
      fi
    else
      # force clean if no stamp found (previous unpack failed)
      printf "%${BUILD_INDENT}c * Removing $i ...\n" ' '>&$SILENT_OUT
      rm -rf $i
    fi
  done
  rm -f $STAMPS/$1/build_*
fi
